/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./lib/public/setup.html",
    "./lib/public/login.html",
    "./lib/public/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        // TeamYou brand scales — mirrored from the teamyou repo's
        // tailwind.config.ts / DESIGN.md. Sync when the brand changes.
        "teamyou-green": {
          50: "#effef4",
          100: "#d8ffea",
          200: "#b4fed5",
          300: "#7afbb5",
          400: "#31ee88",
          500: "#10d76c",
          600: "#06b357",
          700: "#098c47",
          800: "#0d6e3b",
          900: "#0d5a33",
          950: "#00331a",
        },
        "teamyou-cobalt": {
          50: "#e6f2f8",
          100: "#cce5f1",
          200: "#99cbe3",
          300: "#66b1d5",
          400: "#3397c7",
          500: "#007db9",
          600: "#006494",
          700: "#004b6f",
          800: "#023544",
          900: "#012a3a",
          950: "#000d15",
        },
        surface: "var(--bg-sidebar)",
        border: "var(--border)",
        body: "var(--text)",
        bright: "var(--text-bright)",
        "fg-muted": "var(--text-muted)",
        "fg-dim": "var(--text-dim)",
        field: "var(--field-bg-contrast)",
        overlay: "var(--overlay)",
        status: {
          error: "var(--status-error)",
          "error-muted": "var(--status-error-muted)",
          "error-bg": "var(--status-error-bg)",
          "error-border": "var(--status-error-border)",
          warning: "var(--status-warning)",
          "warning-muted": "var(--status-warning-muted)",
          "warning-bg": "var(--status-warning-bg)",
          "warning-border": "var(--status-warning-border)",
          success: "var(--status-success)",
          "success-muted": "var(--status-success-muted)",
          "success-bg": "var(--status-success-bg)",
          "success-border": "var(--status-success-border)",
          info: "var(--status-info)",
          "info-muted": "var(--status-info-muted)",
          "info-bg": "var(--status-info-bg)",
          "info-border": "var(--status-info-border)",
        },
      },
      fontFamily: {
        sans: ["'Geist'", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'Geist Mono'", "ui-monospace", "monospace"],
      },
    },
  },
};
